Create a Linear Regression Model using Python/R to predict home prices using Boston Housing 
Dataset (https://www.kaggle.com/c/boston-housing). The Boston Housing dataset contains 
information about various houses in Boston through different parameters. There are 506 samples and 
14 feature variables in this dataset.
The objective is to predict the value of prices of the house using the given features

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [4]:
df = pd.read_csv('boston-housing/train.csv')
test = pd.read_csv('boston-housing/test.csv')

In [3]:
df

ID     crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0      1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1      2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2      4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
3      5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
4      7  0.08829  12.5   7.87     0  0.524  6.012  66.6  5.5605    5  311   
..   ...      ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
328  500  0.17783   0.0   9.69     0  0.585  5.569  73.5  2.3999    6  391   
329  502  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
330  503  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
331  504  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
332  506  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       18.7  394.63   2.94  33.4  
3       18.7  396.90   5.33  36.2  
4       15.2  395.60  12.43  22.9  
..       ...     ...    ...   ...  
328     19.2  395.77  15.10  17.5  
329     21.0  391.99   9.67  22.4  
330     21.0  396.90   9.08  20.6  
331     21.0  396.90   5.64  23.9  
332     21.0  396.90   7.88  11.9  

[333 rows x 15 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   ID       333 non-null    int64  
 1   crim     333 non-null    float64
 2   zn       333 non-null    float64
 3   indus    333 non-null    float64
 4   chas     333 non-null    int64  
 5   nox      333 non-null    float64
 6   rm       333 non-null    float64
 7   age      333 non-null    float64
 8   dis      333 non-null    float64
 9   rad      333 non-null    int64  
 10  tax      333 non-null    int64  
 11  ptratio  333 non-null    float64
 12  black    333 non-null    float64
 13  lstat    333 non-null    float64
 14  medv     333 non-null    float64
dtypes: float64(11), int64(4)
memory usage: 39.1 KB


In [19]:
x = df.drop(['medv'], axis = 1)
y = df['medv']
x

ID     crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0      1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1      2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2      4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
3      5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
4      7  0.08829  12.5   7.87     0  0.524  6.012  66.6  5.5605    5  311   
..   ...      ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
328  500  0.17783   0.0   9.69     0  0.585  5.569  73.5  2.3999    6  391   
329  502  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
330  503  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
331  504  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
332  506  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       18.7  394.63   2.94  
3       18.7  396.90   5.33  
4       15.2  395.60  12.43  
..       ...     ...    ...  
328     19.2  395.77  15.10  
329     21.0  391.99   9.67  
330     21.0  396.90   9.08  
331     21.0  396.90   5.64  
332     21.0  396.90   7.88  

[333 rows x 14 columns]

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size = 0.2, random_state = 0)

In [35]:
from sklearn.preprocessing import normalize

In [36]:
x_train = normalize(x_train)

In [37]:
x_train

array([[4.20204766e-01, 4.97395214e-03, 0.00000000e+00, ...,
        2.35781563e-02, 4.56085584e-01, 1.47888733e-02],
       [4.98242727e-01, 1.58388741e-05, 1.57339809e-01, ...,
        2.67477674e-02, 6.90057436e-01, 1.37235277e-02],
       [5.19412625e-01, 5.72556672e-02, 0.00000000e+00, ...,
        2.52822531e-02, 1.10478440e-01, 4.62840455e-02],
       ...,
       [3.02420662e-01, 4.06843703e-03, 0.00000000e+00, ...,
        2.58464170e-02, 6.12102936e-01, 2.11518637e-02],
       [1.43157312e-01, 1.77958653e-04, 0.00000000e+00, ...,
        3.87129633e-02, 7.73714865e-01, 1.35495372e-02],
       [4.48496266e-01, 3.81026054e-04, 3.91544359e-02, ...,
        3.39931694e-02, 6.71089234e-01, 6.38929205e-03]])

In [38]:
x_test = normalize(x_test)
x_test

array([[1.70773018e-01, 7.21922604e-05, 5.08253030e-02, 9.88043890e-03,
        0.00000000e+00, 8.66063163e-04, 1.25375857e-02, 9.49416660e-02,
        1.09796886e-02, 8.13204848e-03, 5.71276406e-01, 3.86272303e-02,
        7.94175854e-01, 1.52679210e-02],
       [1.63543924e-01, 8.30439705e-05, 5.04765199e-02, 9.81263547e-03,
        0.00000000e+00, 8.60119899e-04, 1.35822220e-02, 6.76385367e-02,
        1.09043416e-02, 8.07624318e-03, 5.67356084e-01, 3.83621551e-02,
        8.01365230e-01, 1.06808316e-02],
       [5.34198569e-01, 9.17365878e-03, 0.00000000e+00, 2.25384478e-02,
        0.00000000e+00, 8.45503096e-04, 7.71163575e-03, 9.72515343e-02,
        2.41024417e-03, 2.98852346e-02, 8.29315261e-01, 2.51534058e-02,
        1.20449948e-01, 2.67970937e-02],
       [2.65647012e-01, 4.84180640e-03, 0.00000000e+00, 3.46757899e-02,
        0.00000000e+00, 1.54252365e-03, 9.91217549e-03, 1.68066009e-01,
        2.70198430e-03, 8.85490038e-03, 7.13704971e-01, 2.60334071e-02,
        6.231

## Model

In [13]:
from sklearn.linear_model import LinearRegression

In [22]:
model = LinearRegression()

In [39]:
model.fit(x_train, y_train)

LinearRegression()

In [40]:
model.score(x_test, y_test)

0.7421792143304502

In [41]:
test_data = normalize(test)

In [43]:
pred_values = model.predict(test)

C:\Users\prana\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [52]:
pred_values

array([18745.06958992, 15205.36321722, 12420.11441991,  7147.46810169,
       12080.7935807 , 12226.65927463, 13013.43245652, 11563.90839673,
        8982.16698473, 11286.33203441, 14181.61918466, 14965.20702627,
        5432.09371769, 10058.38337043, 15200.99450205, 14068.48595955,
       15030.64092915, 17485.73078864,  5007.17414306, 17157.74260482,
       14694.63127018, 16735.78838771, 14989.2560766 , 14868.50561309,
       16344.43544795, 16946.88979847, 17085.9861923 , 16996.9868365 ,
       18580.74282041, 17535.39382434, 23015.47797105, 22643.83018572,
       20616.32272383, 16575.18253163, 14552.24949675, 16436.2571999 ,
       16188.42428993, 16309.04688036, 15466.26125902, 14036.45239559,
       13988.06528889, 18078.50198793, 18010.53444565, 16346.75484547,
       13862.84892263, 11201.36990297,  8883.4780497 , 10959.39918352,
       14500.95375418, 15847.70149944, 13352.78204062, 23294.67749941,
       28867.88753694, 18110.95952303, 12994.65168798, 14662.70524279,
      